# Nome do compilador
CC = gcc

# Flags de compilação
CFLAGS = -Wall -Wextra -O2

# Nome do executável
TARGET = sort

# Lista de arquivos fonte
SRCS = main.c

# Regra padrão
all: $(TARGET)

# Regra para compilar o executável
$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRCS)

# Regra para limpar os arquivos compilados
clean:
	rm -f $(TARGET)
